### ISSUE TITLE
Feature: Create a git-compatible logger

### ISSUE THREAD

**Issue by ASAAR** [ASAAR/SE2-KaggleComp#1]
This logger should automatically run along with our models and record the score that they are getting, so we have a record of our scores and if we somehow make a mistake down the road, we can revert back to a version with high scores.

It should include the following data,
- model (maybe given via string input)
- score
- date
- time
- user

CLI Arguments:
- Model (using a predefined XML or JSON format)
- Score 

Output:
- Format: XML or JSON (User preference)

**Comment by asclines** [comment]
As for language: I believe bash is the best option. 
We have already determined that a requirement for this project is that it be run on a Unix/Linux environment. In addition, bash will be make handling calling CLI commands such as `git` a breeze.
It is also portable and light and every Unix/Linux system will be able to run it.

**Comment by asclines** [comment]
Output Formation Options:
- XML
- JSON

Any other ideas?
