### ISSUE TITLE
Model Filtering and Selection

### ISSUE THREAD

**Issue by ASAAR** [ASAAR/SE2-KaggleComp#114]
The more fully developed framework needed a way to grab a model from any folder substructure, so I took the old code in ml_runners and upgraded it, allowing it to now return a function that can be called later on from within a worker.

Included,
- model filtering and selection script
- model properties
- model sub-folders to aid with filtering

**Comment by asclines** [comment]
Is this an issue? Your saying this like it's in past test. This reads like a PR message not an issue message.

**Comment by ASAAR** [comment]
Eh, it's like saying that what will be included in the changes I made will be X Y and Z. But yeah, I forgot to make the issue before working on the task.
