### ISSUE TITLE
Strategy Design Pattern Class for Data Filling

### ISSUE THREAD

**Issue by ZakeryFyke** [ASAAR/SE2-KaggleComp#117]
We have a number of options when it comes to data filling that all appear within their own functions. Each is useful in certain situations, but not all. We'd like a Class that can make the decision on which function to run based on the composition of the dataframe it's working with. This class would use the Strategy Design Pattern, and would likely get this composition from functions running within data_insight.py

Not entirely certain how this will work out, but it should be fun.

**Comment by asclines** [comment]
So what would we want this to look like from the outside looking in? We pass in the data frame,variable, and value and let it figure out the rest?

**Comment by ZakeryFyke** [comment]
Good question. As I understand it right now, we will give the class a dataframe to work with. It will call data_insight and run a function to get the composition of the dataframe (For the fillers, the only important parts are the missing data ratio and the dtypes of each column). Then, based on the composition of the dataframe, the class will decide which datafillers should be run. 

For example, if the missing to data ratio is over, say, 90%, we might want to delete that column. If it's between, say, 25% and 75%, we may want to fill it in with a value. And if it's < 25%, we may want to fill it in with the average of that column. (I made up all these numbers just now, I imagine it's something we'd put in the config)
