### ISSUE TITLE
Test folder is getting cluttered

### ISSUE THREAD

**Issue by asclines** [ASAAR/SE2-KaggleComp#120]
If anyone visits `/tests/` they might notice that the directory is getting really cluttered and seemingly unorganized. 

Something needs to be done. First off I have a question though, why do we separate all the tests out into their own directory? @ASAAR , I believe you are the one who created that structure?

If there isn't any good reason to continue keeping the tests separated into their own part of the project, I recommend that we migrate the tests to accompany the modules they are apart of. An example of that type of organization can be found in the [MLTA](https://github.com/ASAAR/SE2-KaggleComp/tree/master/modules/MLTA) module.

However, if we decided the tests do need to be separated out, can we please restructure the organization of tests in the `/tests/` directory?

**Comment by ZakeryFyke** [comment]
Would we want to move each test into the same directory of the modules they are testing, or would we perhaps want to put them into their own directory within that directory?
For a folder like data_kit, I feel having all the tests in that same directory would be a lot of clutter, but putting a test directory in data_kit holding all the tests would be more manageable

**Comment by asclines** [comment]
@ZakeryFyke look at the MLTA module for what I'm thinking of.

**Comment by RyanMcBerg** [comment]
Im all for having the test folder in the same directory as what is being tested.  It would make  pathing easier for me at least, and would likely declutter it a little

**Comment by ZakeryFyke** [comment]
@asclines I like that structure.

**Comment by ASAAR** [comment]
I'm good with this, we should probably add a section to documentation about testing standards to keep it somewhat standard

**Comment by ZakeryFyke** [comment]
If we're still wanting to move all the tests into their own sub directories, I could handle this later tonight unless @asclines or @ASAAR have a particular way they want something done. I was just going to follow the same structure as found in the MLTA module.

**Comment by ASAAR** [comment]
@ZakeryFyke go ahead! Thank you!
