### ISSUE TITLE
Configuration: Providing test/train files

### ISSUE THREAD

**Issue by asclines** [ASAAR/SE2-KaggleComp#122]
Configuration should have two methods:
`get_test_files()` and `get_train_files()`   
These two methods should return a list of files. So if the passed in data is a folder, the method should return a list of all the files in that folder

**Comment by RyanMcBerg** [comment]
Will these two functions be to populate the ticket fields with filepaths, or will they be to actually bring in the data?

**Comment by asclines** [comment]
These methods are intended for the hub to access.  As for how the ticket gets this data will be left to the hub to decide.  @assar thoughts?

**Comment by ASAAR** [comment]
Yeah these are just for hub access, the hub will then load the data and pass that data along with each ticket.

**Comment by ASAAR** [comment]
moving to next iter

**Comment by asclines** [comment]
This should have been closed in #129 sorry.
