### ISSUE TITLE
Fixing code climate nagging

### ISSUE THREAD

**Issue by ZakeryFyke** [ASAAR/SE2-KaggleComp#133]
After moving the tests around, Code Climate has raised a number of complaints about them. I'll remedy the ones I can.

**Comment by RyanMcBerg** [comment]
Is there anything that can actually be done about these issues?

**Comment by ZakeryFyke** [comment]
Dunno, gonna find out

**Comment by ZakeryFyke** [comment]
So it _can_ be done, and I'm making attempts to do so now, but I'm a bit worried that it reduces the overall readability of the actual code. I'll get y'all's feedback on it, though, to be sure.

**Comment by asclines** [comment]
Well get the code on a PR and we will be happy to give feedback
