### ISSUE TITLE
get_missing_ratios fails with multiple missing columns

### ISSUE THREAD

**Issue by ASAAR** [ASAAR/SE2-KaggleComp#140]
I get,
`"cannot convert the series to <type 'float'>"`

When there are multiple columns in the dataset that have missing columns.

Happy Thanksgiving :)

**Comment by ZakeryFyke** [comment]
@ASAAR it fails when the dataset has multiple empty columns, or when the dataset has multiple columns containing missing values?

**Comment by ASAAR** [comment]
@ZakeryFyke when a dataset has multiple columns containing empty values.

Steps for replication,
1. Merge the training and test data for titanic: `data = pandas.concat([train, test])`
2. Select data that doesn't have missing values: `data_splitting.remove_non_numeric_columns(data)`

= FUN

**Comment by ZakeryFyke** [comment]
@ASAAR I've used those steps, and also attempted by adding empty columns and emptying out values from existing columns, but I'm not able to replicate this issue. 
Also, does step 2 in your replication select data with no missing values? If so, that's a very interesting naming scheme.

**Comment by ASAAR** [comment]
@ZakeryFyke my bad, fixed the instructions

**Comment by ASAAR** [comment]
@ZakeryFyke Issue fixed, it happened to be caused my something I did. Essentially if I had two datasets.

A with indices 0, 1, 2, 3, 4, 5 and B with 0, 1, 2. If I concat them, then it becomes 0, 1, 2, 3, 4, 5, 0, 1, 2 **unless** I use "ignore_index=True" in the concat command. Not doing that messed up your function.
