### ISSUE TITLE
Continuous Integration 

### ISSUE THREAD

**Issue by asclines** [ASAAR/SE2-KaggleComp#161]
It's time we looked into bring a continuous integration tool into our pipeline. [GitHub](https://github.com/integrations/feature/continuous-integration) provides some good integrations with C.I. tools.  
Let's discuss.

**Comment by ZakeryFyke** [comment]
Do you have any experience with the CI tools that GitHub provides? I've not messed with them before.

**Comment by asclines** [comment]
I have mild experience with Travis CI and it comes highly recommended by several people I know. It seems to be general and thorough enough to cover all we need. Also their [guides](https://docs.travis-ci.com/user/for-beginners) are pretty easy to follow.

**Comment by isaac-gs** [comment]
Who wants to own this? I'm happy to do it

**Comment by asclines** [comment]
Is this a 1 person task? Seeing as we all need to write out tests into this?

**Comment by isaac-gs** [comment]
I see what you mean. I was thinking someone could manage figuring it out and dealing with any issues

**Comment by asclines** [comment]
@ASAAR Fair enough that makes sense. Yeah you can tackle that problem. I'm assuming we are all good with using Travis CI?

**Comment by ZakeryFyke** [comment]
@asclines I have no objections.

**Comment by isaac-gs** [comment]
You'll need this when setting up Travis-CI on a machine. But this is mostly for posterity.

https://github.com/travis-ci/travis.rb/issues/391

**Comment by asclines** [comment]
lol ive been dealing with gem errors all day in another project. [https://rvm.io/](https://rvm.io/) is our friend here.
