### ISSUE TITLE
Checking test coverage

### ISSUE THREAD

**Issue by asclines** [ASAAR/SE2-KaggleComp#165]
In order to keep this repo going well, another thing we should look into is test coverage.   
Now [CodeClimate](https://docs.codeclimate.com/docs/setting-up-test-coverage) does offer code coverage testing, but it might not be right for us. 
My main concern _against_ using CodeClimate for test coverage is that it is not multi-language friendly. 

But it _is_ something we have already integrated with out project so it would be the easiest to setup. Thoughts?

**Comment by asclines** [comment]
Here is another option I've seen in other repos: https://coveralls.io/

**Comment by isaac-gs** [comment]
Yeah, I like the idea of using coveralls. Mainly because if we want to, we can support multiple languages.

https://github.com/lemurheavy/coveralls-public/issues/373

Also, it integrates with Travis CI

**Comment by isaac-gs** [comment]
@RyanMcBerg @ZakeryFyke Either of you have a preference?

**Comment by ZakeryFyke** [comment]
I'm pro anything that's pro multiple languages.
