### ISSUE TITLE
Splitter in R as opposed to Python

### ISSUE THREAD

**Issue by RyanMcBerg** [ASAAR/SE2-KaggleComp#20]
I wrote the splitter in python, but there are tools in R that would likely make this more efficient that I know of in R.  I may rewrite this as an rscript, and we can compare to see which is faster?

**Comment by Zak7062** [comment]
That sounds like a good idea to me; how long does the splitter take to run as is? Is time a large concern for it?

**Comment by RyanMcBerg** [comment]
I can be with larger datasets.. it seems like Python treats datasets as lists, and randomizing large lists could take a long time, unless there is something i'm missing.

**Comment by Zak7062** [comment]
Can't hurt then.

**Comment by RyanMcBerg** [comment]
My plan is to implement it again at the beginning of Sprint 2 to replace the current Splitter.py. If anyone has any objections feel free to voice them
