### ISSUE TITLE
Logging datasets

### ISSUE THREAD

**Issue by asclines** [ASAAR/SE2-KaggleComp#21]
The logger module should have a way to log information about the chosen dataset. 
This story is still in the early stages of planning.

To-Do:
- Plan out what about the dataset needs to be logged

**Comment by ASAAR** [comment]
@asclines there isn't an estimate on this task

**Comment by asclines** [comment]
I estimate this issue to be irrelevant now.

**Comment by asclines** [comment]
But for reals, #38 Will handle this indirectly.
