### ISSUE TITLE
Proportion of missing data.

### ISSUE THREAD

**Issue by telelu03** [ASAAR/SE2-KaggleComp#30]
Given a column and ap. Proportion by the user, return a boolean indicating whether or not the column has that proportion of missing values.

**Comment by ZakeryFyke** [comment]
@RyanMcBerg is this done?

**Comment by ASAAR** [comment]
@RyanMcBerg bump

**Comment by RyanMcBerg** [comment]
Um. No. Is this assigned to me?

**Comment by RyanMcBerg** [comment]
Ah. I see that it is. I will take care of it.

**Comment by RyanMcBerg** [comment]
Decided to close the issue for this iteration since we have the dimensionality reduction in place, and want to focus on getting the tests to work as well as other functionality.
