### ISSUE TITLE
Explore Image Processing/ML in Scikit

### ISSUE THREAD

**Issue by telelu03** [ASAAR/SE2-KaggleComp#35]
Explore algorithms that deal with Image Processing in SciKit.

Write a script to be able to take in images, and output a classification of the image.

Explore options with Image Processing in Azure ML

**Comment by ASAAR** [comment]
Because of the amount of learning you'll need to do for this. I'd actually call it an 8 @telelu03

**Comment by telelu03** [comment]
Just changed the estimate.
