### ISSUE TITLE
Feature: Cross-file feature selector

### ISSUE THREAD

**Issue by ASAAR** [ASAAR/SE2-KaggleComp#4]
We have the problem of having almost 7 GB of training data across 3 files (with 4000+ independent variables), we need a script that will allow us to select the most important features across those files without putting everything into memory at once.

Possibly worth reading,
- http://www.cs.colostate.edu/pubserv/pubs/Bins-draper-publications-bins_iccv01.pdf

**Comment by ZakeryFyke** [comment]
Is this still something we're working on?

**Comment by ASAAR** [comment]
@ZakeryFyke We should....I just don't know when it'll happen

**Comment by ZakeryFyke** [comment]
Alright, I've got it tossed into the sprint backlog. We can move it to Icebox if need be.

**Comment by ZakeryFyke** [comment]
No longer relevant
