### ISSUE TITLE
Launcher: Settings and Saved Options

### ISSUE THREAD

**Issue by ASAAR** [ASAAR/SE2-KaggleComp#49]
We need a module that controls settings and saved options. Such as target training and test files so that the user doesn't need to type them in over and over again. Or a saved location for each.

Needs,
- Saved names of files or locations for training and test files.
- Type of prediction being used
- Type of separator used in the data files
- Easy to add more options

**Comment by asclines** [comment]
@ASAAR , is this going to be handled by the configuration options that @ZakeryFyke has created currently and in the future be handled by the configuration manager I will be creating?

**Comment by ASAAR** [comment]
@asclines Yeah, it will be, and the separator is not even necessary anymore. Should I close it?

**Comment by ASAAR** [comment]
This issue is no longer relevant, now owned by Alex's work.
