### ISSUE TITLE
Image classification: Example

### ISSUE THREAD

**Issue by ASAAR** [ASAAR/SE2-KaggleComp#57]
Setup and run these two examples, for the second you'll need to download tensorflow. If you want to, you can make an examples folder at the top level of the project for this content. @telelu03 

Example 1: http://scikit-learn.org/stable/auto_examples/classification/plot_digits_classification.html
Example 2: https://www.tensorflow.org/versions/r0.11/tutorials/mnist/beginners/index.html#mnist-for-ml-beginners

**Comment by ZakeryFyke** [comment]
@ASAAR @telelu03 is this something we'd like to move to iteration 3?

**Comment by telelu03** [comment]
Yeah @ASAAR we can continue parts of this. I want to actually split it up into an Issue with Image Processing and an Issue with applying Image Classification algorithms.

**Comment by ZakeryFyke** [comment]
This is still chilling in Review/QA after like 3 weeks. What are our plans for this issue?

**Comment by asclines** [comment]
Is it supposed to be in review/qa?  Is it even in progress?

**Comment by telelu03** [comment]
My fault. In the backlog I split it into a couple different issues, I forgot to reflect that here. Its still in progress.

**Comment by ZakeryFyke** [comment]
@telelu03 I am going to close this issue then; will you create your split issues for your image processing/classification when you have time?

**Comment by telelu03** [comment]
Yeah I will create separate issues for everything.
