### ISSUE TITLE
Bug: Models not being saved

### ISSUE THREAD

**Issue by ASAAR** [ASAAR/SE2-KaggleComp#59]
I'm trying to use pickle to save models and it's entirely ineffective. It should work, because scikit suggests it. Some other people have had the same issue.

**Comment by ASAAR** [comment]
I might need to change the way all of this works, if I can't pass models back through return statements, we have a problem

**Comment by asclines** [comment]
Why can't you pass models back through return statements?

**Comment by ASAAR** [comment]
@asclines because when I try to run them, it claims they haven't been trained (fitted)

**Comment by ASAAR** [comment]
Looks like I have to rebuild a lot of stuff to avoid this issue. I'm also running into the following bug (in the process).
![bug](https://cloud.githubusercontent.com/assets/1311843/19118716/f020b642-8ae2-11e6-8797-02defc31e7d6.PNG)
