### ISSUE TITLE
Analyzer-FirebaseUpload: Remove Firebase mock server from testing

### ISSUE THREAD

**Issue by asclines** [ASAAR/SE2-KaggleComp#68]
Currently, `test-firebase-config` uses a module called [firebase-server](https://github.com/urish/firebase-server). However, this module has been causing me more headaches than @RyanMcBerg's _commit_ment issues and the documentation for it has misled me more than Appple Maps. Therefore something needs to change. 

Until firebase-server updates to work with Firebase 3.0 or another firebase mock server is found, the tests using a mock server should be replaced with tests that simply mock the firebase calls. Examples of this can be found in the other tests that use firebase.

**Comment by asclines** [comment]
Update: After looking into this more, in order to test the firebase-config-manager without a mock server would still require mocking a lot of methods in the firebase module provided by firebase. With that,  and given the fact that it appears that firebase-server has acknowledged the issues and is working on it, it may be better to wait for firebase-server to update instead of rolling out our own mock.

**Comment by asclines** [comment]
That being said, it might be worth it to roll out a mock firebase testing module that doesnt act as a mock server but simply mocks the methods.

**Comment by ASAAR** [comment]
@asclines how long before there's an update to firebase-server? Also, could we just test the capability of the system to send something to firebase and get it back? We might be able to save time here

**Comment by asclines** [comment]
@ASAAR Who knows. 
Yes we could test the capability of the system by sending and retrieving stuff with our firebase, but I don't want to:
  a) Have to rely on an internet connection and that server for testing
  b) Clutter our firebase data with test junk anymore

As of now, we are fine as the code has been manually tested and seems to be mock-tested enough to be good. As long as there are no more modifications to the code. Once that code starts getting worked on again, I offer no guarantee that the current testing is sufficient. 

I think it will be worth it to **not** make our own mock firebase and to just wait it out.
