### ISSUE TITLE
Feature: Baselines (including data) for validating ML algorithms

### ISSUE THREAD

**Issue by ASAAR** [ASAAR/SE2-KaggleComp#7]
We need a data set that people have explored and already have results for so that we can validate our results against it.

Requirements
- Data set which we have results for already. So we know what to expect for it and can test our results against it.
- A basic testing file which demonstrates what these tests might look like.

**Comment by Zak7062** [comment]
[This](http://archive.ics.uci.edu/ml/datasets/Wine+Quality)wine data set looks like it might be useful to validate our results against.
