### ISSUE TITLE
Configuration Options Single Instance Class

### ISSUE THREAD

**Issue by ASAAR** [ASAAR/SE2-KaggleComp#85]
We need a python class which mocks a configuration options module. It should request the following options and give functions to retrieve those configurations.

Options,
- Training file name (including extension)
- Test file name (including extension)
- Separator for file
- Prediction type
- Target column, or column that should be predicted

**Comment by ZakeryFyke** [comment]
@ASAAR Are we still intending this to be designed as a singleton class?

**Comment by asclines** [comment]
@ZakeryFyke No, there should be no singletons in this project.

**Comment by ZakeryFyke** [comment]
Good, gooood.

**Comment by asclines** [comment]
That being said, this issue should be updated to reflect our recent decision to ban singletons.

**Comment by ASAAR** [comment]
Nope, we'll just use it as single instance.

________________________________

**Comment by ASAAR** [comment]
@ZakeryFyke @asclines Is this closed?

**Comment by ZakeryFyke** [comment]
@ASAAR I had moved it to Review/QA until our product owner has marked it as done.
