### ISSUE TITLE
Detail: Create a list of setup instructions (iteration one)

### ISSUE THREAD

**Issue by Zak7062** [ASAAR/SE2-KaggleComp#9]
We want to have a list of setup instructions for Bash for users who don't already have it set up

**Comment by ASAAR** [comment]
@asclines @Zak7062 @RyanMcBerg @telelu03 Can anyone think of anything else we need for now? I'll add more over time.

**Comment by RyanMcBerg** [comment]
@ASAAR Since my "Demo" uses R we should maybe have some R setup instructions?
