### ISSUE TITLE
CodeClimate configuration file missing

### ISSUE THREAD

**Issue by asclines** [ASAAR/SE2-KaggleComp#90]
In order to customize how CodeClimate checks the code we need a `.codeclimate.yml` file somewhere. Not sure how this all works so I'm passing it on to our in-house CodeClimate expert @ASAAR .

### Steps to reproduce issue
For any issue on [CodeClimate ](https://codeclimate.com/github/ASAAR/SE2-KaggleComp/issues) select **Disable Checks** > **Ignore this issue**

**Comment by ASAAR** [comment]
In order for this to work, it seems like you need to use Docker because their CLI tool is deployed using it. Bash on Ubuntu on Windows isn't recognizing Docker
